export const inntektTyper = [
  'Aksjer/grunnfondsbevis til underkurs',
  'Annen arbeidsinntekt',
  'Arbeidsopphold kost',
  'Arbeidsopphold losji',
  'Beregnet skatt',
  'Besøksreiser hjemmet annet',
  'Besøksreiser hjemmet kilometergodtgjørelse bil',
  'Betalt utenlandsk skatt',
  'Bil',
  'Bolig',
  'Bonus',
  'Bonus fra forsvaret',
  'Elektronisk kommunikasjon',
  'Fast bilgodtgjørelse',
  'Faste tillegg',
  'Fastlønn',
  'Feriepenger',
  'Fond for idrettsutøvere',
  'Foreldrepenger fra folketrygden',
  'Helligdagstillegg',
  'Honorar, akkord, prosent eller provisjonslønn',
  'Hyretillegg',
  'Innbetaling til utenlandsk pensjonsordning',
  'Kilometergodtgjørelse bil',
  'Kommunal omsorgslønn og fosterhjemsgodtgjørelse',
  'Kost (dager)',
  'Kost (døgn)',
  'Kostbesparelse i hjemmet',
  'Losji',
  'Lønn mv som ikke er skattepliktig i Norge fra utenlandsk diplomatisk eller konsulær stasjon',
  'Lønn og godtgjørelse til dagmamma eller praktikant som passer barn i barnets hjem',
  'Lønn og godtgjørelse til privatpersoner for arbeidsoppdrag i oppdragsgivers hjem',
  'Lønn og godtgjørelse utbetalt av veldedig eller allmennyttig institusjon eller organisasjon',
  'Lønn til verge fra Fylkesmannen',
  'Opsjoner',
  'Overtidsgodtgjørelse',
  'Reise annet',
  'Reise kost',
  'Reise losji',
  'Rentefordel lån',
  'Skattepliktig del av visse typer forsikringer',
  'Sluttvederlag',
  'Smusstillegg',
  'Stipend',
  'Styrehonorar og godtgjørelse i forbindelse med verv',
  'Svangerskapspenger',
  'Timelønn',
  'Trekk i lønn for ferie',
  'Uregelmessige tillegg knyttet til arbeidet tid',
  'Uregelmessige tillegg knyttet til ikke-arbeidet tid',
  'Yrkebil tjenestligbehov kilometer',
  'Yrkebil tjenestligbehov listepris',
  'Dagpenger ved arbeidsløshet',
  'Dagpenger til fisker',
  'Dagpenger til fisker som bare har hyre',
  'Sykepenger til fisker',
  'Sykepenger til fisker som bare har hyre',
  'Annen næringsinntekt',
  'Hyre - Annet',
  'Hyre - Bonus',
  'Hyre - Faste tillegg',
  'Hyre - Fastlønn',
  'Hyre - Feriepenger',
  'Hyre - Helligdagstillegg',
  'Hyre - Overtidsgodtgjørelse',
  'Hyre - Sluttvederlag',
  'Hyre - Timelønn',
  'Hyre - Uregelmessige tillegg knyttet til arbeidet tid',
  'Hyre - Uregelmessige tillegg knyttet til ikke-arbeidet tid',
  'Lott det skal beregnes trygdeavgift av',
  'Trekk i lønn for ferie - Hyre',
  'Vederlag lott',
  'Sykepenger fra folketrygden',
  'Sykepenger fra næring',
  'Sykepenger til dagmamma',
  'Sykepenger til jord- og skogbrukere',
  'Tiltak - Annet',
  'Tiltak - Bonus',
  'Tiltak - Faste tillegg',
  'Tiltak - Fastlønn',
  'Tiltak - Feriepenger',
  'Tiltak - Helligdagstillegg',
  'Tiltak - Overtidsgodtgjørelse',
  'Tiltak - Sluttvederlag',
  'Tiltak - Timelønn',
  'Tiltak - Uregelmessige tillegg knyttet til arbeidet tid',
  'Tiltak - Uregelmessige tillegg knyttet til ikke-arbeidet tid',
  'Trekk i lønn for ferie - Tiltak',
];

export const aktoerType = [
  'ORGANISASJON',
  'PRIVATPERSON',
];

export default { inntektTyper, aktoerType };
