version: '3.3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dp-inntekt-db
  dp-inntekt-api:
    build: ./../dp-inntekt-api
    hostname: dp-inntekt-api
    ports:
      - "8099:8099"
    environment:
      DATABASE_HOST: postgres
      JWKS_URL: "http://host.docker.internal:4352/certs"
      JWKS_ISSUER: "http://simple-oidc-provider"
    depends_on:
      - postgres
    external_links:
      - dp-inntekt-api
  dagpenger-oppslag:
    build: ./../dagpenger-oppslag
    hostname: dagpenger-oppslag
    ports:
      - "8080:8080"
    environment:
      SRVDAGPENGER_OPPSLAG_USERNAME: foo
      SRVDAGPENGER_OPPSLAG_PASSWORD: bar
      JWKS_URL: "http://host.docker.internal:4352/certs"
      JWT_ISSUER: "http://simple-oidc-provider"
      JOURNALFOERINNGAAENDE_V1_URL: "http://localhost"
      VIRKSOMHET_PERSON_V3_ENDPOINTURL: "http://localhost"
      SECURITYTOKENSERVICE_URL: "http://localhost"
      AKTOR_URL: "http://localhost"
  dp-regel-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      APP_INNTEKT_BASEURL: "http://dp-inntekt-api:8099/"
      APP_OPPSLAG_BASEURL: "http://dagpenger-oppslag:8080/"
      APP_GRAPHQL_BASEURL: "http://host.docker.internal:4000"
      OIDC_HOST_URL: "http://host.docker.internal:4352"
      OIDC_REDIRECT_URI: "http://localhost:3000/inntekter/oidc/callback"
      OIDC_AGENTNAME: "foo"
      OIDC_PASSWORD: "bar"
      REDIS_HOST: redis
    depends_on:
      - dp-inntekt-api
    links:
      - dp-inntekt-api
      - redis
  redis:
    image: redis
  oidc-provider:
    image: qlik/simple-oidc-provider
    ports:
      - 4352:4352
    environment:
      - REDIRECTS=http://localhost:3000/inntekter/oidc/callback
      - PORT=4352
  echo-server:
    image: mendhak/http-https-echo
    ports:
      - 3340:80

