version: '3.3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dp-inntekt-db
  dp-inntekt-api:
    build: ./../dp-inntekt-api
    hostname: dp-inntekt-api
    ports:
      - "8099:8099"
    environment:
      DATABASE_HOST: postgres
    depends_on:
      - postgres
    external_links:
      - dp-inntekt-api
  dp-regel-ui:
    build: .
    ports:
      - "80:80"
    environment:
      APP_INNTEKT_BASEURL: "http://dp-inntekt-api:8099/"
    depends_on:
      - dp-inntekt-api
    links:
      - dp-inntekt-api
