version: '3.3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dp-inntekt-db
  dp-inntekt-api:
    build: ./../dp-inntekt
    hostname: dp-inntekt-api
    ports:
      - "8099:8099"
    environment:
      DATABASE_HOST: postgres
      JWKS_URL: "http://host.docker.internal:4352/certs"
      JWKS_ISSUER: "http://simple-oidc-provider"
    depends_on:
      - postgres
    external_links:
      - dp-inntekt-api
  dp-regel-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      APP_INNTEKT_BASEURL: "http://dp-inntekt-api:8099/"
      APP_OPPSLAG_BASEURL: "https://data.brreg.no/"
      OIDC_HOST_URL: "http://host.docker.internal:4352"
      OIDC_REDIRECT_URI: "http://localhost:3000/inntekter/oidc/callback"
      OIDC_AGENTNAME: "foo"
      OIDC_PASSWORD: "bar"
      REDIS_HOST: redis
    depends_on:
      - dp-inntekt-api
    links:
      - dp-inntekt-api
      - redis
  redis:
    image: redis
  oidc-provider:
    image: qlik/simple-oidc-provider
    ports:
      - 4352:4352
    environment:
      - REDIRECTS=http://localhost:3000/inntekter/oidc/callback
      - PORT=4352
  echo-server:
    image: mendhak/http-https-echo
    ports:
      - 3340:80

