apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dagpenger-regel-ui
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dagpenger-regel-ui
spec:
  image: {{image}}
  port: 3000
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: APP_INNTEKT_BASEURL
      value: http://dp-inntekt-api.teamdagpenger.svc.nais.local/
  webproxy: true
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: false
  liveness:
    path: /api/isalive
  readiness:
    path: /api/isready
  prometheus:
    enabled: false
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
