apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dagpenger-regel-ui
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dagpenger-regel-ui
spec:
  image: {{image}}
  port: 3000
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  webproxy: true
  env:
    - name: INNTEKT_API
      value: https://{{inntekt_api.ingress}}
    - name: INNTEKT_API_AUDIENCE
      value: {{inntekt_api.audience}}
  accessPolicy:
    outbound:
      external:
        - host: {{inntekt_api.ingress}}
  azure:
    application:
      enabled: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: false
  liveness:
    path: /api/isalive
  readiness:
    path: /api/isready
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
