apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dagpenger-regel-ui
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dagpenger-regel-ui
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
spec:
  image: {{image}}
  port: 3000
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  webproxy: true
  env:
    - name: INNTEKT_API
      value: https://{{inntekt_api.ingress}}
    - name: INNTEKT_API_AUDIENCE
      value: {{inntekt_api.audience}}
  accessPolicy:
    outbound:
      external:
        - host: {{inntekt_api.ingress}}
  azure:
    application:
      allowAllUsers: true
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  liveness:
    path: /api/isalive
  readiness:
    path: /api/isready
  prometheus:
    enabled: true
    path: /api/internal/metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 128Mi
