apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-soknadsdialog
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-soknadsdialog
  annotations:
    nais.io/security-does-not-matter: "true"
spec:
  image: {{image}}
  port: 443
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: APP_INNTEKT_BASEURL
      value: http://dp-inntekt-api.teamdagpenger.svc.nais.local/
    - name: REDIS_HOST
      value: dagpenger-redis.teamdagpenger.svc.nais.local
    - name: REDIS_PORT
      value: "6379"
    - name: OIDC_HOST_URL
      value: {{ oidc.host_url }}
    - name: OIDC_AGENTNAME
      value: {{ oidc.agentname }}
  webproxy: true
  azure:
    application:
      enabled: true
      replyURLs:
        - "https://my-app.dev.nav.no/oauth2/callback"
  liveness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
