apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-regel-ui
spec:
  ingresses:
    - "https://dagpenger-regel-ui.nais.adeo.no/"
  env:
    - name: APP_INNTEKT_BASEURL
      value: http://dp-inntekt-api/
    - name: REDIS_HOST
      value: dagpenger-redis.default.svc.nais.local
    - name: REDIS_PORT
      value: "6379"
    - name: OIDC_HOST_URL
      value: https://isso.adeo.no:443/isso/oauth2
    - name: OIDC_AGENTNAME
      value: dagpenger-regel-ui-p
