query($aktoerId: String!, $aktoerType: String!) {
    aktoer(aktoerId: $aktoerId, aktoerType: $aktoerType) {
      __typename
      ... on Person {
        navn
        naturligIdent
      }
      ... on Organisasjon {
        organisasjonsnummer
        navn
      }
    }
  }
