# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  nais: navikt/nais-deployment@1.1.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run: yarn build:css

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn test:less
      # Build artifact for docker
      - run: yarn build
      - nais/docker-deploy:
          image: navikt/dagpenger-regel-ui


workflows:
  version: 2
  dagpenger-regel-ui:
    jobs:
      - build:
          context: NAIS deployment
      - nais/deploy:
          name: dev_deploy
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/dagpenger-regel-ui
          image: navikt/dagpenger-regel-ui
          filters:
            branches:
              only: master
          requires:
            - build
          github-app-id: 21626
          nais-template: nais/nais-dev.yaml
          team: teamdagpenger
          environment: dev-fss

      - nais/deploy:
          name: prod_deploy
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/dagpenger-regel-ui
          image: navikt/dagpenger-regel-ui
          filters:
            branches:
              only: master
          requires:
            - dev_deploy
          github-app-id: 21626
          nais-template: nais/nais-dev.yaml
          team: teamdagpenger
          environment: prod-fss



