apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-regel-ui
spec:
  image: repo.adeo.no:5443/dagpenger-regel-ui:latest
  port: 443
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  liveness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 200m
      memory: 256Mi
