query($personId: ID!, $vedtakId: ID!, $beregningsdato: String!) {
    person(id: $personId) {
      navn
      fornavn
      aktoerId
      naturligIdent
      vedtak(id: $vedtakId, beregningsdato: $beregningsdato) {
        id
        aktoerId
        beregningsdato
        inntekt(forceRefresh: true) {
          id
          timestamp
          manueltRedigert
          redigertAvSaksbehandler
          fraDato
          tilDato
          posteringer {
            id
            beloep
            fordel
            aarMaaned
            virksomhet {
              __typename
              ... on Person {
                navn
                naturligIdent
              }
              ... on Organisasjon {
                organisasjonsnummer
                navn
              }
            }
            inntektsmottaker {
              ... on Person {
                navn
                naturligIdent
              }
              ... on Organisasjon {
                organisasjonsnummer
                navn
              }
            }
          }
        }
      }
    }
  }
