apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-regel-ui
  namespace: default
  labels:
    team: teamdagpenger
spec:
  ingresses:
    - "https://dagpenger-regel-ui.nais.adeo.no/"
  env:
    - name: APP_INNTEKT_BASEURL
      value: http://dp-inntekt-api/
    - name: APP_OPPSLAG_BASEURL
      value: https://data.brreg.no/enhetsregisteret/
    - name: REDIS_HOST
      value: dagpenger-redis.default.svc.nais.local
    - name: REDIS_PORT
      value: "6379"
    - name: OIDC_HOST_URL
      value: https://isso.adeo.no:443/isso/oauth2
    - name: OIDC_AGENTNAME
      value: dagpenger-regel-ui-p
  image: {{image}}
  port: 443
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  webproxy: true
  liveness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
