apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dagpenger-redis
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: dagpenger-redis
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
spec:
  image: {{redis_image}}
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
