query($personId: ID!, $vedtakId: ID!, $beregningsdato: String!, $forceRefresh: Boolean) {
    person(id: $personId) {
      navn
      fornavn
      aktoerId
      naturligIdent
      identifikator
      kjoenn
      alder
      vedtak(id: $vedtakId, beregningsdato: $beregningsdato) {
        id
        aktoerId
        beregningsdato
        inntekt(forceRefresh: $forceRefresh) {
          id
          timestamp
          manueltRedigert
          redigertAvSaksbehandler
          fraDato
          tilDato

          posteringer {
            id
            beloep
            fordel
            verdikode,
            beskrivelse,
            aarMaaned
            inngaarIGrunnlagForTrekk
            utloeserArbeidsgiveravgift
            informasjonsstatus
            inntektType
            utbetaltIMaaned
            leveringstidspunkt
            inntektsperiodetype
            inntektsstatus
            inntektskilde
            virksomhet {
              __typename
              ... on Person {
                navn
                naturligIdent
                identifikator
                aktoerType
              }
              ... on Organisasjon {
                aktoerType
                organisasjonsnummer
                identifikator
                navn
              }
            }
            inntektsmottaker {
              ... on Person {
                navn
                naturligIdent
                identifikator
                aktoerType
              }
              ... on Organisasjon {
                organisasjonsnummer
                navn
                identifikator
                aktoerType
              }
            }
          }
        }
      }
    }
  }
