name: Build and deploy redis

on:
  push:
    branches:
      - master
    paths:
      - redis/**
      - .github/workflows/deploy-redis.yaml
      - nais/redis.yaml

env:
  IMAGE: ghcr.io/${{ github.repository }}/dagpenger-redis:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push redis image
        uses: docker/build-push-action@v2
        with:
          context: redis
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Archive NAIS yaml
        uses: actions/upload-artifact@v2
        with:
          name: redis-nais-yaml
          path: nais/redis.yaml

  deploy-preprod:
    name: Deploy to Preprod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/redis.yaml
          VARS: nais/vars.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy to Prod
    needs: [build, deploy-preprod]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/redis.yaml
          VARS: nais/vars.yaml
          PRINT_PAYLOAD: true
